# Generated by Django 2.2.13 on 2021-11-04 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('estatus', models.BooleanField(verbose_name='Estatus')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Dirección',
            },
        ),
        migrations.CreateModel(
            name='ServiciosSolicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('estatus', models.BooleanField(verbose_name='Estatus')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Direccion')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('appaterno', models.CharField(max_length=30, verbose_name='apellido paterno')),
                ('apmaterno', models.CharField(max_length=30, verbose_name='apellido materno')),
                ('curp', models.CharField(max_length=50, verbose_name='CURP')),
                ('estcivil', models.CharField(max_length=50, verbose_name='estcivil')),
                ('discapacidad', models.CharField(max_length=50, verbose_name='discapacidad')),
                ('domicilio', models.CharField(max_length=50, verbose_name='domicilio')),
                ('correo', models.CharField(max_length=50, verbose_name='correo')),
                ('telefono', models.CharField(max_length=50, verbose_name='teléfono')),
                ('estatus', models.BooleanField(default=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('servicios', models.ManyToManyField(blank=True, to='home.ServiciosSolicitud')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitud',
            },
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
    ]
