# Generated by Django 2.2.13 on 2021-11-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211104_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='sexo',
            field=models.CharField(max_length=50, null=True, verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='estatus',
            field=models.BooleanField(default=True, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='serviciossolicitud',
            name='estatus',
            field=models.BooleanField(default=True, verbose_name='Estatus'),
        ),
    ]
