# Generated by Django 2.2.13 on 2021-11-06 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211105_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoblacionObjetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('estatus', models.BooleanField(default=True, verbose_name='Estatus')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Población Objetivo',
                'verbose_name_plural': 'Poblaciones objetivo',
            },
        ),
        migrations.AddField(
            model_name='solicitud',
            name='poblacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.PoblacionObjetivo'),
        ),
    ]
