# Generated by Django 2.2.13 on 2021-11-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211105_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='apmaterno',
            field=models.CharField(max_length=100, verbose_name='apellido materno'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='appaterno',
            field=models.CharField(max_length=100, verbose_name='apellido paterno'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='correo',
            field=models.CharField(max_length=200, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='telefono',
            field=models.CharField(max_length=200, verbose_name='teléfono'),
        ),
    ]
