# Generated by Django 2.2.13 on 2021-11-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211108_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='calle',
            field=models.CharField(max_length=50, null=True, verbose_name='calle'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='codigo',
            field=models.CharField(max_length=50, null=True, verbose_name='código postal'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='exterior',
            field=models.CharField(max_length=50, null=True, verbose_name='exterior'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='domicilio',
            field=models.CharField(max_length=100, verbose_name='domicilio'),
        ),
    ]
