# Generated by Django 2.2.13 on 2021-11-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211110_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciossolicitud',
            name='seguimiento',
            field=models.BooleanField(default=False, verbose_name='¿Necesita seguimiento?'),
        ),
    ]
