# Generated by Django 2.2.13 on 2021-11-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211125_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviciossolicitud',
            name='cantidad',
            field=models.CharField(default='0', max_length=200, null=True, verbose_name='cantidad de stock para la feria'),
        ),
        migrations.AlterField(
            model_name='serviciossolicitud',
            name='limite',
            field=models.BooleanField(default=False, null=True, verbose_name='¿Tiene limite de stock para la feria?'),
        ),
    ]
