# Generated by Django 2.2.13 on 2021-11-29 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_registroimpresion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroimpresion',
            options={'verbose_name': 'Registro de impresiones', 'verbose_name_plural': 'Registro de impresiones'},
        ),
    ]
