# Generated by Django 2.2.25 on 2022-02-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20211129_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='calle',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='calle'),
        ),
    ]
